### Pilots GET all
GET http://localhost:8080/api/pilots

### Pilots GET succesful
GET http://localhost:8080/api/pilots/1

### Pilots GET 404
GET http://localhost:8080/api/pilots/999

### Pilots POST/PUT (new entity)
POST http://localhost:8080/api/pilots
Content-Type: application/json

{
  "id": 45,
  "name" : "Jan",
  "surname" : "Nowak",
  "dateOfBirth" : "1998-12-07"
}

### Pilots PUT (update existing)
PUT http://localhost:8080/api/pilots/45
Content-Type: application/json

{
  "name": "Jan",
  "surname": "Kowalski",
  "dateOfBirth": "2001-03-03"
}

### Pilots DELETE
DELETE http://localhost:8080/api/pilots/45


### Licenses GET all
GET http://localhost:8080/api/licenses

### Licenses GET (existing)
GET http://localhost:8080/api/licenses/1

### Licenses POST/PUT
POST http://localhost:8080/api/licenses
Content-Type: application/json

{
  "id" : 3,
  "privilegeLevel" : "ATP",
  "issueDate" : "2022-10-20",
  "description" : "Airline Transport Pilot",
  "pilotId" : 2
}

### Licenses PUT (update)
PUT http://localhost:8080/api/licenses/3
Content-Type: application/json

{
  "privilegeLevel" : "ATP",
  "issueDate" : "2022-10-20",
  "description" : "Airline Transport Pilot (modified)",
  "pilotId" : 1
}

### Licences DELETE
DELETE http://localhost:8080/api/licenses/3

### Combined GET all from pilot 1
GET http://localhost:8080/api/pilots/1/licenses

### Combined GET
GET http://localhost:8080/api/pilots/1/licenses/1

### Combined POST/PUT (new entity)
POST http://localhost:8080/api/pilots/1/licenses
Content-Type: application/json

{
  "id": 34,
  "privilegeLevel" : "commercial",
  "issueDate" : "2022-10-20",
  "description" : "A commercial license"
}

### Combined PUT update
PUT http://localhost:8080/api/pilots/1/licenses/34
Content-Type: application/json

{
  "privilegeLevel" : "commercial",
  "issueDate" : "2022-10-20",
  "description" : "A commercial license with more text"
}

### Combined DELETE

DELETE http://localhost:8080/api/pilots/1/licenses/34


### Combined DELETE all licenses

DELETE http://localhost:8080/api/pilots/1/licenses


